services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust" # Consider removing this and setting a password
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: valkey/valkey
    restart: unless-stopped
  web:
    image: glitchtip/glitchtip
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
      EMAIL_URL: ${EMAIL_URL}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      CELERY_WORKER_AUTOSCALE: ${CELERY_WORKER_AUTOSCALE}
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
      EMAIL_URL: ${EMAIL_URL}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      CELERY_WORKER_AUTOSCALE: ${CELERY_WORKER_AUTOSCALE}
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  migrate:
    image: glitchtip/glitchtip
    depends_on:
      - postgres
      - redis
    command: ./bin/run-migrate.sh
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
      EMAIL_URL: ${EMAIL_URL}
      GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      CELERY_WORKER_AUTOSCALE: ${CELERY_WORKER_AUTOSCALE}

volumes:
  pg-data:
  uploads:
